preprocessing:
  TRAIN_DATA_PATH: ./../../Blood_data/train/
  TEST_DATA_PATH: ./../../Blood_data/test/
  BACKBONE_MODEL_PATH: ./../../wubinray/base/checkpoints/resnet18/best_0.75.pth
  BACKBONE_MDOEL_NAME: resnet18
  device: cuda
  TRAIN_EMBEDDING_SAVE: ./train_embedding.pkl
  TEST_EMBEDDING_SAVE: ./test_embedding.pkl

LSTM_TRAINING: 
  FIX_SPLIT: true
  TRAIN_DATA_PATH: ./../../Blood_data/train/
  TRAIN_EMBEDDING: ./train_embedding.pkl
  TEST_EMBEDDING: ./test_embedding.pkl
  TRAIN_LABEL_CSV: ./../../Blood_data/train.csv

  BATCH_SIZE: 64
  MAX_EPOCH: 50 
  N_CLASS: 5
  DEVICE: cuda
  OPTIMIZER: Adam
  LEARNING_RATE: 0.001
  
  LSTM_EMBEDDING_SIZE: 512
  LSTM_UNITS: 64

LSTM_INFERENCE:
  MODEL_PATH: ./experiment/lstm_best.pth
  TEST_DATA_PATH: ./../../Blood_data/test/
  TEST_EMBEDDING: ./test_embedding.pkl

  N_CLASS: 5
  BATCH_SIZE: 64
  DEVICE: cuda
  OUTPUT_CSV: ./lstm_basic.csv
  THRESHOLD: 0.5